all:
	g++ -o kruskal.bin kruskal.cpp
	mv kruskal.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh

ignore:
	g++ -o kruskal.bin ignore.cpp
	mv kruskal.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh

ignore2:
	g++ -o kruskal.bin ignore2.cpp
	mv kruskal.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh

testelocal:
	g++ -o kruskal.bin kruskal.cpp
	./kruskal.bin -f entrada.in
	
testelocal2:
