all:
	g++ -o dijkstra.bin dijkstra.cpp
	mv dijkstra.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh && rm dijkstra.bin

ignore:
	g++ -o dijkstra.bin ignore.cpp
	mv dijkstra.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh

ignore2:
	g++ -o dijkstra.bin ignore2.cpp
	mv dijkstra.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh

testelocal:
	g++ -o dijkstra.bin dijkstra.cpp
	./dijkstra.bin -f entrada.in
	
testelocal2:
