all: 
	g++ carraghan-pardalos.cpp -o carraghan-pardalos.cpp.bin

clean: 
	rm carraghan-pardalos.cpp.bin

run:
	./carraghan-pardalos.cpp.bin < inputs/input.txt
	./carraghan-pardalos.cpp.bin < inputs/input2.txt