all: 
	g++ carraghan-pardalos.cpp -o carraghan-pardalos.cpp.bin; echo ""
	./carraghan-pardalos.cpp.bin < inputs/input_1.mtx; echo ""
	./carraghan-pardalos.cpp.bin < inputs/input_2.mtx; echo ""
	./carraghan-pardalos.cpp.bin < inputs/input_3.mtx; echo ""
	./carraghan-pardalos.cpp.bin < inputs/input_4.mtx; echo ""
	./carraghan-pardalos.cpp.bin < inputs/input_5.mtx; echo ""
	rm carraghan-pardalos.cpp.bin

build: 
	g++ carraghan-pardalos.cpp -o carraghan-pardalos.cpp.bin
	
clean: 
	rm carraghan-pardalos.cpp.bin

run:
	./carraghan-pardalos.cpp.bin < inputs/input_1.mtx; echo ""
	./carraghan-pardalos.cpp.bin < inputs/input_2.mtx; echo ""
	./carraghan-pardalos.cpp.bin < inputs/input_3.mtx; echo ""
	./carraghan-pardalos.cpp.bin < inputs/input_4.mtx; echo ""
	./carraghan-pardalos.cpp.bin < inputs/input_5.mtx; echo ""
	
