all:
	g++ -o prim.bin prim.cpp
	mv prim.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh && rm prim.bin

ignore:
	g++ -o prim.bin ignore.cpp
	mv prim.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh

ignore2:
	g++ -o prim.bin ignore2.cpp
	mv prim.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh

testelocal:
	g++ -o prim.bin prim.cpp
	./prim.bin -f entrada.in
	
testelocal2:
